Feature reviews
TyJacalan/booking-app pull request #44
Opened 2024-05-29 07:29 UTC by shinichikudo000

Added Review, Comment, and Like models along with their respective controllers.
Introduced is_completed boolean and review_notification attribute in the Appointment model.
Adjusted associations in User, Appointment, Review, Comment, and Like models for consistency.
Resolved seeding issues to ensure data integrity.

Issues to be Fixed:

Adjusted migration file order so that Appointment migrations precede Review migrations for logical consistency.
Added JavaScript controllers and their corresponding view files; these files should be ignored for now as they still need to be fixed for views.

To-do
Views and stream for likes, comments and forms
![image](https://github.com/TyJacalan/booking-app/assets/118242519/5a367082-b1dc-4f22-9cf4-f4323e031b76)

![image](https://github.com/TyJacalan/booking-app/assets/118242519/39e30af1-a7f8-4c26-a3a9-3c43a72be113)

2024-05-29 12:03 UTC, p3rc1us approved these changes

2024-05-29 15:56 UTC, cimafrancamae commented on app/assets/images/communication.png
can we use icons for these images instead? we have font-awesome installed: https://fontawesome.com/icons

2024-05-29 15:56 UTC, cimafrancamae commented on app/components/shadcn/select_component.rb
this component is being used by other forms, have you confirmed that this doesn't affect the others?

2024-05-29 15:56 UTC, cimafrancamae commented on config/routes.rb
Have you merged dev here? The collection under `resources :services` is gone

2024-05-29 16:06 UTC, cimafrancamae commented
Is there anything I need to configure locally?
I ran `rails db:seed` and it returned an error:

<img width="867" alt="image" src="https://github.com/TyJacalan/booking-app/assets/65450522/2f770ea2-e906-4132-ae49-f01ce8750f52">


Then `rails assets:precompile` returned this error:

<img width="867" alt="image" src="https://github.com/TyJacalan/booking-app/assets/65450522/b1c98d60-b031-4b6b-974d-c0e2cadf4bb3">

2024-05-29 16:11 UTC, cimafrancamae commented on config/routes.rb
please don't remove this on the routes:

```
resources :services do
    collection do
      post :category, to: 'categories#select', as: :select_category_new
      post :set_detail, to: 'service_details#set', as: :set_detail
      get :new_form, to: 'service_details#show', as: :detail
    end
  end
```

2024-05-30 02:38 UTC, shinichikudo000 commented on app/assets/images/communication.png
naka svg siya. ill try to use na lang icons. nakalimutan lang idelete yung files ng png

2024-05-30 02:46 UTC, shinichikudo000 commented on app/components/shadcn/select_component.rb
not sure wala siya sa merging issues ko sa vscode. ininstall ko lang siya so yung akin is from shadcn. ill fix na lang

2024-05-30 02:46 UTC, shinichikudo000 commented on config/routes.rb
nag merge ako sa dev. and wala namang akong finix sa routes. not sure bakit wala

2024-05-30 10:54 UTC, cimafrancamae approved these changes
This PR is already working on my end! 🚀

2024-05-30 13:06 UTC, TyJacalan requested changes
Generally good commit, lots of new features and we can now use Redis throughout the application. Checklist before approving this PR:
1. revert file: [select_helper](app/helpers/components/select_helper.rb)
2. revert file: [service reference migration](db/migrate/20240517100503_add_service_reference_to_appointments.rb)
3. Delete unused [file](app/javascript/controllers/hello_controller.js)

On a final note, please refrain from large commits. The smaller the better so it's easier to review and address comments. This could have been staggered between installing redis, creating reviews, setting up the different models, etc. This took a while so thanks for your patience on this.

2024-06-07 15:33 UTC, merged