Implement New Search Bar, clean Merge with Refactor/Service to Resolve Issue #96
TyJacalan/booking-app pull request #97
Opened 2024-06-05 08:17 UTC by p3rc1us

## Sample
![image](https://github.com/TyJacalan/booking-app/assets/144686514/b1bff49f-dcbb-44ec-9a47-7335bcb19c1f)
## PR Summary
- Changed search bar to prevent turbo frame redundancy #96
- New style for search bar
- Included select input for Category
- Divided search inputs for What (Service), Where (City), Who (Freelancer)

2024-06-06 05:54 UTC, shinichikudo000 approved these changes

2024-06-06 06:17 UTC, TyJacalan requested changes
Good to go after reverting the muted color change. Feel free to introduce a new color in the config.

The mobile responsiveness issues can be worked on in a future commit.

2024-06-06 06:17 UTC, TyJacalan commented on app/views/services/_search_form.html.erb
looks better but review the mobile responsiveness

2024-06-06 06:28 UTC, p3rc1us commented on app/assets/stylesheets/shadcn.css
> -    --muted: 60 4.8% 95.9%;
@cimafrancamae e68c4d5bc38439878e17b88a2100ab7fa390d022

2024-06-06 07:21 UTC, TyJacalan commented on app/assets/stylesheets/shadcn.css
> -    --muted: 60 4.8% 95.9%;
I can update the notifications styles if you've already used `muted` extensively. I'm not sure where else I've used it though and some components from shadcn may be using it too.

2024-06-06 07:38 UTC, p3rc1us commented on app/views/services/_search_form.html.erb
I'll follow it up. I'm struggling with tw

2024-06-07 03:50 UTC, cimafrancamae commented on app/assets/stylesheets/shadcn.css
> -    --muted: 60 4.8% 95.9%;
It's okay to revert the muted color. Has this been worked out na? @TyJacalan @p3rc1us

2024-06-07 03:50 UTC, cimafrancamae approved these changes

2024-06-07 08:55 UTC, TyJacalan approved these changes

2024-06-07 10:14 UTC, merged